// SPDX-FileCopyrightText: 2022-2025 Alexey Rochev
//
// SPDX-License-Identifier: MIT

package org.equeim.spacer.ui.theme

import androidx.compose.ui.graphics.Color

object Colors {
    val primaryLight = Color(0xFF65558F)
    val onPrimaryLight = Color(0xFFFFFFFF)
    val primaryContainerLight = Color(0xFFE9DDFF)
    val onPrimaryContainerLight = Color(0xFF211047)
    val secondaryLight = Color(0xFF65558F)
    val onSecondaryLight = Color(0xFFFFFFFF)
    val secondaryContainerLight = Color(0xFFE9DDFF)
    val onSecondaryContainerLight = Color(0xFF201047)
    val tertiaryLight = Color(0xFF136682)
    val onTertiaryLight = Color(0xFFFFFFFF)
    val tertiaryContainerLight = Color(0xFFBEE9FF)
    val onTertiaryContainerLight = Color(0xFF001F2A)
    val errorLight = Color(0xFFBA1A1A)
    val onErrorLight = Color(0xFFFFFFFF)
    val errorContainerLight = Color(0xFFFFDAD6)
    val onErrorContainerLight = Color(0xFF410002)
    val backgroundLight = Color(0xFFFDF7FF)
    val onBackgroundLight = Color(0xFF1D1B20)
    val surfaceLight = Color(0xFFFDF7FF)
    val onSurfaceLight = Color(0xFF1D1B20)
    val surfaceVariantLight = Color(0xFFE7E0EB)
    val onSurfaceVariantLight = Color(0xFF49454E)
    val outlineLight = Color(0xFF7A757F)
    val outlineVariantLight = Color(0xFFCAC4CF)
    val scrimLight = Color(0xFF000000)
    val inverseSurfaceLight = Color(0xFF322F35)
    val inverseOnSurfaceLight = Color(0xFFF5EFF7)
    val inversePrimaryLight = Color(0xFFCFBDFE)
    val surfaceDimLight = Color(0xFFDED8E0)
    val surfaceBrightLight = Color(0xFFFDF7FF)
    val surfaceContainerLowestLight = Color(0xFFFFFFFF)
    val surfaceContainerLowLight = Color(0xFFF8F2FA)
    val surfaceContainerLight = Color(0xFFF2ECF4)
    val surfaceContainerHighLight = Color(0xFFECE6EE)
    val surfaceContainerHighestLight = Color(0xFFE6E0E9)

    val primaryDark = Color(0xFFCFBDFE)
    val onPrimaryDark = Color(0xFF36265D)
    val primaryContainerDark = Color(0xFF4D3D75)
    val onPrimaryContainerDark = Color(0xFFE9DDFF)
    val secondaryDark = Color(0xFFCFBDFE)
    val onSecondaryDark = Color(0xFF36275D)
    val secondaryContainerDark = Color(0xFF4D3D75)
    val onSecondaryContainerDark = Color(0xFFE9DDFF)
    val tertiaryDark = Color(0xFF8BD0F0)
    val onTertiaryDark = Color(0xFF003546)
    val tertiaryContainerDark = Color(0xFF004D64)
    val onTertiaryContainerDark = Color(0xFFBEE9FF)
    val errorDark = Color(0xFFFFB4AB)
    val onErrorDark = Color(0xFF690005)
    val errorContainerDark = Color(0xFF93000A)
    val onErrorContainerDark = Color(0xFFFFDAD6)
    val backgroundDark = Color(0xFF141218)
    val onBackgroundDark = Color(0xFFE6E0E9)
    val surfaceDark = Color(0xFF141218)
    val onSurfaceDark = Color(0xFFE6E0E9)
    val surfaceVariantDark = Color(0xFF49454E)
    val onSurfaceVariantDark = Color(0xFFCAC4CF)
    val outlineDark = Color(0xFF948F99)
    val outlineVariantDark = Color(0xFF49454E)
    val scrimDark = Color(0xFF000000)
    val inverseSurfaceDark = Color(0xFFE6E0E9)
    val inverseOnSurfaceDark = Color(0xFF322F35)
    val inversePrimaryDark = Color(0xFF65558F)
    val surfaceDimDark = Color(0xFF141218)
    val surfaceBrightDark = Color(0xFF3B383E)
    val surfaceContainerLowestDark = Color(0xFF0F0D13)
    val surfaceContainerLowDark = Color(0xFF1D1B20)
    val surfaceContainerDark = Color(0xFF211F24)
    val surfaceContainerHighDark = Color(0xFF2B292F)
    val surfaceContainerHighestDark = Color(0xFF36343A)
}
