# SPDX-FileCopyrightText: 2022-2025 Alexey Rochev
#
# SPDX-License-Identifier: CC0-1.0

version = 1
SPDX-PackageName = "Spacer"
SPDX-PackageSupplier = "Alexey Rochev <equeim@gmail.com>"
SPDX-PackageDownloadLocation = "https://github.com/equeim/spacer"

[[annotations]]
path = ["donki/src/test/resources/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 Alexey Rochev"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["gradle/wrapper/gradle-wrapper.jar", "gradle/wrapper/gradle-wrapper.properties"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2015-2021 the original authors"
SPDX-License-Identifier = "Apache-2.0"
